TASK: VlspEvjVqaTask

DATASET:
  FEATURE_DATASET:
    TYPE: MultilingualFeatureDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: /content/vinvl_vinvl
      IMAGE: /content/train-images
  DICT_DATASET:
    TYPE: MultilingualDictionaryDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: /content/vinvl_vinvl
      IMAGE: /content/train-images
  MIN_FREQ: 1
  VOCAB:
    TYPE: VlspVqaMultiModalVocab
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    PRETRAINED_LANGUAGE_MODEL: bert-base-multilingual-cased
  JSON_PATH:
    TRAIN: /content/drive/MyDrive/VQA/ENVJ_VQA/Data/Splitted_Data/train_data.json
    DEV: /content/drive/MyDrive/VQA/ENVJ_VQA/Data/Splitted_Data/dev_data.json
    PUBLIC_TEST: /content/drive/MyDrive/VQA/ENVJ_VQA/Data/official_evjvqa_public_test.json
    PRIVATE_TEST: null

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 1
  PATIENCE: 5

MODEL:
  ARCHITECTURE: JointTransformer
  NAME: joint_transformer_vlsp
  DEVICE: cuda
  REGION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: .1
  GRID_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 1024
    D_MODEL: 512
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    DEVICE: cuda
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
  D_MODEL: 512
  DROPOUT: .1
  ENCODER:
    ARCHITECTURE: Encoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1