TASK: TrainingMMF

DATASET:
  FEATURE_DATASET:
    TYPE: OcrFeatureDataset
    BATCH_SIZE: 64
    WORKERS: 2
    FEATURE_PATH:
      FEATURES: features\x152++_faster_rcnn
      SCENE_TEXT: features\swintextspotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.0
    MAX_SCENE_TEXT: 100
    WORD_EMBEDDING: ViFastText
    WORD_EMBEDDING_CACHE: null
  DICT_DATASET:
    TYPE: OcrDictionaryDataset
    BATCH_SIZE: 64
    WORKERS: 2
    FEATURE_PATH:
      FEATURES: features\x152++_faster_rcnn
      SCENE_TEXT: features\swintextspotter
      IMAGE: null
    SCENE_TEXT_THRESHOLD: 0.0
    MAX_SCENE_TEXT: 100
    WORD_EMBEDDING: ViFastText
    WORD_EMBEDDING_CACHE: null
  MIN_FREQ: 1
  VOCAB:
    TYPE: OcrVocab
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    MIN_FREQ: 1
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    OCR_TOKEN: <ocr>
    OCR_DET_TOKEN: <ocr_det>
    OCR_REC_TOKEN: <ocr_rec>
    QUESTION_TOKEN: <question>
    ANSWER_TOKEN: <answer>
    JSON_PATH:
      TRAIN: annotations\openvivqa_train_v2.json
      DEV: annotations\openvivqa_dev_v2.json
      TEST: annotations\openvivqa_test_v2.json
  JSON_PATH:
    TRAIN: annotations\openvivqa_train_v2.json
    DEV: annotations\openvivqa_dev_v2.json
    TEST: annotations\openvivqa_test_v2.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 1
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 1
  EVALUATING_BEAM_SIZE: 1
  PATIENCE: 5

MODEL:
  ARCHITECTURE: MMF_IterativeLoRRA
  NAME: mmf_iterative_lorra_x152++_faster_rcnn
  DEVICE: cuda
  D_MODEL: 512
  SCENE_TEXT_THRESHOLD: 0.3
  MAX_SCENE_TEXT: 50
  OBJECT_EMBEDDING:
    D_FEATURE: 1024
    DROPOUT: .1
  BOX_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    DEVICE: cuda
    D_FEATURE: 4
    D_MODEL: 512
    DROPOUT: .1
  OCR_EMBEDDING:
    D_FEATURE: 300 # (fasttext)
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: UsualEmbedding
    DEVICE: cuda
    D_EMBEDDING: 300
    D_MODEL: 512
    DROPOUT: .1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null  
  SELF_ATTENTION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 1
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  SPATIAL_ATTENTION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 1
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  CONTEXT_ATTENTION:
    ARCHITECTURE: ScaledDotProductAttention
    HEAD: 1
    D_MODEL: 512
    D_KEY: 64
    D_VALUE: 64
    D_FF: 2048
    D_FEATURE: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: False
    DROPOUT: .1
  OCR_PTR_NET:
    HIDDEN_SIZE: 512
    QUERY_KEY_SIZE: 512
  CLASSIFIER:
    OCR_MAX_NUM: 30
  MMT:
    HIDDEN_SIZE: 512
    NUM_HIDDEN_LAYERS: 4
    NUM_ATTENTION_HEADS: 8